### ISSUE TITLE
Code signing issue

### ISSUE THREAD

**Issue by daviddelmonte** [borchero/WebParsing#1]
This is a great control, and I appreciate your work. I have no problem using WP in the simulator. I get " Use of unresolved identifier 'WPJson'" when I try to compile for a phone. I've turned on Code signing in the WP project. Not sure what else to do! Any help appreciated.

**Comment by borchero** [comment]
I'll have a look, thanks for your report! What about simply copying the files into your project? That should work. But I'll tell you as soon as I find a reason for this behavior.

**Comment by borchero** [comment]
Sorry it took so long; it should work now.
